Repository eyre-rs/eyre, pull requests merged in 2023-12, with the labels that each got.

#143 Fix invalid drop impl call in `Report::downcast`
  eyre/src/error.rs
  eyre/tests/drop/mod.rs
  eyre/tests/test_context.rs
  eyre/tests/test_convert.rs
  eyre/tests/test_downcast.rs
  eyre/tests/test_repr.rs
Labels: C-bug, A-eyre

#140 fix: `ok_or_eyre` not using `track_caller`
  eyre/src/option.rs
  eyre/tests/test_location.rs
Labels: C-bug

#139 fix(docs): fix two `rustdoc::bare_urls` warnings
  eyre/src/lib.rs
Labels: C-documentation
